version: '3.8'

services:
  couchbase:
    image: couchbase:community
    ports:
      - "8091:8091"    # Couchbase web console
      - "8092:8092"    # Couchbase views
      - "8093:8093"    # Couchbase query service
      - "8094:8094"    # Couchbase search service
      - "11210:11210"  # Data service
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
  couchbase_data:

